# Generated by Django 4.1 on 2022-08-26 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('steps', models.IntegerField()),
                ('time', models.TimeField()),
                ('distance', models.IntegerField()),
                ('img', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trashcan',
            fields=[
                ('address', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('trashcan_x', models.FloatField()),
                ('trashcan_y', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('address', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('trash_x', models.FloatField()),
                ('trash_y', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
