# Generated by Django 4.1 on 2022-09-02 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('address', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('trash_x', models.FloatField()),
                ('trash_y', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
