# Generated by Django 4.1 on 2022-09-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trash',
            old_name='user_id',
            new_name='user',
        ),
    ]
