# Generated by Django 4.1 on 2022-09-05 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trashcan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trashcan_x', models.FloatField()),
                ('trashcan_y', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
