# Generated by Django 4.1 on 2022-09-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
