# Generated by Django 4.1 on 2022-09-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='image',
        ),
    ]
