# Generated by Django 4.1 on 2022-08-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=10)),
                ('board_img', models.ImageField(null=True, upload_to='')),
                ('content', models.TextField()),
                ('liked', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commnet',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('board_idx', models.IntegerField()),
                ('writer', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
