# Generated by Django 4.1 on 2022-09-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="comment_cnt",
            field=models.IntegerField(default=0),
        ),
    ]
