# Generated by Django 4.1 on 2022-09-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_remove_profile_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="board",
            name="comment_cnt",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="board",
            name="like_cnt",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
