# Generated by Django 4.1 on 2022-09-10 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0005_profile_nickname_alter_board_comment_cnt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="like_users",
            field=models.ManyToManyField(
                blank=True, related_name="like_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
