# Generated by Django 4.1 on 2022-09-10 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0009_rename_board_like_board"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.TextField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="board",
            name="liked_users",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.AddField(
            model_name="profile",
            name="like_posts",
            field=models.ManyToManyField(
                blank=True, related_name="like_users", to="community.board"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
