# Generated by Django 4.1 on 2022-09-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0015_remove_board_like_user_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="like_posts",
        ),
        migrations.AddField(
            model_name="profile",
            name="like_posts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
