# Generated by Django 4.1 on 2022-09-11 06:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0017_alter_profile_like_posts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="Liked",
        ),
    ]
