# Generated by Django 4.1 on 2022-09-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0018_rename_profile_liked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="board_img",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
