# Generated by Django 4.1 on 2022-09-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0019_alter_board_board_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="board_img",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
