# Generated by Django 4.1 on 2022-09-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0020_alter_board_board_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="board_img",
        ),
    ]
